server:
  port: 8050
  servlet:
    context-path: /

spring:
  application:
    name: learning-server
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# spring-doc-openapi项目配置
spring-doc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '默认分组'
      paths-to-match: '/**'
      packages-to-scan: com.tzy

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    enable-footer: false
